Raspberry Pi wireless you-name-it controller
============================================

This project is sort of a template for anyone who wants their RPi to become
a wireless cotroller for... um... anything, really.

WORK IN PROGRES
---------------

It's very premature, now. Working on it..


How it works
------------

`Nginx` reverse proxy running on the RPi + `uWSGI`\`Flask`\`wipi` application.
Collection of `wipi.controller.Controller` interface implementations is instantiated
(if allowed in the configuration).
The web app. backend translates API calls to the controllers get/set invocations.

So, you can control the back-end devices from your smartphone or anywhere on your
LAN (or the RPi may act as an AP, creating separate LAN of its own).

The API also has support for down-streaming data, e.g. from sensors.
You may set the stream to get data only from one controller, or from a collection
of them.
The stream is facilitated by using chunked encoding of the HTTP response.


`systemd` cheatsheat
--------------------

Restart:
----
# systemctl restart wipi
----

Log:
----
# journalctl -elfu wipi
----


Author
------

Václav Krpec <vencik@razdva.cz>
